<?php 
	include("assets/php/sentientprofiles/assetdata.php");
	include("assets/php/sentientprofiles/galaxydata.php");
	include("assets/php/sentientprofiles/viewTransactions.php");
	include("assets/php/sentientprofiles/viewSkills.php");
	include("assets/php/sentientprofiles/affiliations.php");
	include("assets/php/sentientprofiles/associations.php");
	include("assets/php/sentientprofiles/notes.php");
?>